name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  ENV: dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Load environment variables from GitHub Secrets
      env:  # Cargar secretos del ambiente dev
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
      run: |
        echo "MONGO_URI=${MONGO_URI}" >> $GITHUB_ENV
        echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV
        echo "SECRET_KEY=${SECRET_KEY}" >> $GITHUB_ENV
        echo "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}" >> $GITHUB_ENV
        echo "AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}" >> $GITHUB_ENV
        echo "AUTH0_DOMAIN=${AUTH0_DOMAIN}" >> $GITHUB_ENV
        echo "AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest --maxfail=5 --disable-warnings
